### ISSUE TITLE
About the function of make_csv_action_0149

### ISSUE THREAD

**Issue by JiajiaStrive** [InwoongLee/TS-LSTM#8]
How can I deal with the problem below when I execute the function of make_csv_action_0149?
Looking forward to your reply!

>> skeleton0149
未定义函数或变量 'read_skeleton_file'。

出错 make_csv_action_0149 (line 39)
        sklt_info = read_skeleton_file(strcat(root_path, sklt_file_name));

出错 skeleton0149 (line 4)
make_csv_action_0149( root_path, output_path, sklt_info_txt );

**Comment by InwoongLee** [comment]
If you downloaded raw skeleton txt files from ROSE Lab, you need read_skeleton_file.m
read_skeleton_file.m is provided in https://github.com/InwoongLee/NTURGB-D/blob/master/Matlab/read_skeleton_file.m
Now, I uploaded read_skeleton_file.m in https://github.com/InwoongLee/TS-LSTM/tree/master/NTU_Data_Info

**Comment by JiajiaStrive** [comment]
Thank you very much! I am very glad to receive your reply.
Now, I have another question about the path of  " feature_train = np.load('./sklt_npy_subject_TPAMI/feature_train_{0}_all.npy'.format(view_subject))".

When I execute the code, I get a error reminder which is "IOError: [Errno 2] No such file or directory: './sklt_npy_subject_TPAMI/feature_train_{0}_all.npy'".

How can I deal with this problem?
Looking forward to your reply!

**Comment by InwoongLee** [comment]
It took much times to pre-process the NTU RGB-D dataset, so we saved the './sklt_npy_subject_TPAMI/feature_train_{0}_all.npy'.format(view_subject).
In order to reduce the confusion, I edited CS_Ensemble TS-LSTM v1.py and CV_Ensemble TS-LSTM v1.py files.
First, you have to save './sklt_npy_subject_TPAMI/feature_train_{0}_all.npy'.format(view_subject), and then you can use the saved npy files.
Please refer the commits of https://github.com/InwoongLee/TS-LSTM/commit/c0afaa64b59b814f3da7012e286faa4e888ef216 and https://github.com/InwoongLee/TS-LSTM/commit/a7b478baa00c67517187e1be14e486e40c320eec.
Be careful to set the data paths. You may need making folder.

**Comment by JiajiaStrive** [comment]
I am very glad to receive your reply!
Do I have to execute the update first ? And then I execute the old one?
For example, I execute the new  CS_Ensemble TS-LSTM v1.py which you edited not long ago, and then I execute the old  CS_Ensemble TS-LSTM v1.py.
Looking forward to your reply!

**Comment by InwoongLee** [comment]
You just excute  the new CS_Ensemble TS-LSTM v1.py  not  the old CS_Ensemble TS-LSTM v1.py.
If you want to use the new CS_Ensemble TS-LSTM v1.py again, then you can use just the old CS_Ensemble TS-LSTM v1.py for saving pre-processing time. CS means cross subject, and CV means cross view. You just need to execute the save code one time at each CS and CV test. After that, you can use the saved npy files at each CS and CV test. Ensemble TS-LSTM v1 and v2 use the same input files  at each CS and CV test.
Inputs of Ensemble TS-LSTM v3 and Generalized TS-LSTM is different from those of Ensemble TS-LSTM v1 and v2.
Inputs of Ensemble TS-LSTM v3 are the same as those of Generalized TS-LSTM.
Inputs of Ensemble TS-LSTM v1 are the same as those of Ensemble TS-LSTM v2.

**Comment by JiajiaStrive** [comment]
I see.
Thank you very much!
